path<-"/home/vaibhav/household_power_consumption.txt"
table<-read.table(path,header=TRUE,sep=";",stringsAsFactors=FALSE,dec=".")
req_info<-table[table$Date %in% c("1/2/2007","2/2/2007"),]
req<-strptime(paste(req_info$Date,req_info$Time,sep=" "),"%d/%m/%Y %H:%M:%S") 
pow<-as.numeric(req_info$Global_active_power)
r_pow<- as.numeric(req_info$Global_reactive_power)
v<-as.numeric(req_info$Voltage)
s1<-as.numeric(req_info$Sub_metering_1)
s2<-as.numeric(req_info$Sub_metering_2)
s3<-as.numeric(req_info$Sub_metering_3)
png("plot4.png",width=480,height=480)
par(mfrow=c(2, 2)) 
plot(req,pow,type="l",xlab="",ylab="Global Active Power",cex=0.2)
plot(req,v,type="l",xlab="datetime",ylab="Voltage")
plot(req,s1,type="l",ylab="Energy Submetering",xlab="")
lines(req,s2,type="l",col="red")
lines(req,s3,type="l",col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=,lwd=2.5,col=c("black","red","blue"),bty="o")
plot(req,r_pow,type="l",xlab="datetime",ylab="Global_reactive_power")
dev.off()